language: node_js
sudo: false
node_js:
  - "6.10.3"
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-4.8
     - g++-4.8
env:
 - TRAVIS=travis CXX=g++-4.8